# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/our-brand-447716-f1/dtumlopsartifacts/dtumlops_baseimage:latest
        env:
        - name: WANDB_API_KEY
          value: $WANDB_API_KEY
