name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}


    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.11"]


    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
        pip install .
    - name: Test with pytest
      run: |
        pytest -v

  post-build:
    # This job runs only after all matrix builds complete successfully
    # Builds docker image in google-cloud
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
        pip install .
    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authenticate DVC with Google Cloud
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/google_credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS="/tmp/google_credentials.json"

    - name: Pull data with DVC
      run: |
        dvc pull

    - name: Submit build
      run: gcloud builds submit --config cloudbuild_containers.yaml --substitutions=_LOCATION='europe-west1',_REPOSITORY="dtumlopsartifacts",_IMAGE_NAME="dtumlops_baseimage"
